# Generated by Django 5.1.1 on 2024-11-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='length',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
