# Generated by Django 5.1.1 on 2024-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
